project:
  type: book

book:
  navbar:
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  
  title: "MB 360 Lab Workbook"
  subtitle: "MB 360: Scientific Inquiry in Microbiology At the Bench – Microbial Metabolism and Genomics"
  author:
    - name: "Carlos C. Goller"
      degree: "Ph.D."
      department: "Department of Biological Sciences"
      affiliation: "North Carolina State University"
    - name: "Camila Loyola"
      degree: "Graduate Student Teaching Assistant"
      department: "Master of Microbial Biotechnology Graduate Program"
      affiliation: "North Carolina State University"
  date: "4/17/2026"
  chapters:
    - index.qmd
    - about.qmd
    - figures.qmd
    - module-01.qmd
    - module-02.qmd
    - module-03.qmd
    - module-04.qmd
    - module-05.qmd
    - module-06.qmd
    - module-07.qmd
    - module-08.qmd
    - appendix-supplies-reagents.qmd
    - references.qmd
  
  search:
    location: navbar
    type: overlay

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    lightbox: true
  pdf:
    documentclass: scrreprt



