project:
  type: book
  output-dir: _book

book:
  title: "MB 360 Workbook"
  site-url: "https://ccgoller.github.io/mb360workbook/"
  repo-url: "https://github.com/ccgoller/mb360workbook"
  repo-branch: "main"
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true

execute:
  freeze: auto
